### ISSUE TITLE
能否支持子板块呢？

### ISSUE THREAD

**Issue by onlymash** [kidozh/DiscuzHub#1]
例如
https://masiro.moe

该论坛帖子全都在子板块，如果不能将子板块加载显示出来，便无法看到帖子。

**Comment by kidozh** [comment]
我使用Discuz Hub在匿名模式下访问了这个论坛，发现是可以正常显示的，也没有发现子版块。

我不知道你说的子版块是不是指的是[一亩三分地](https://www.1point3acres.com/bbs/forum-87-1.html)这种，这种我会在2.0这个版本中加入支持。

**Comment by onlymash** [comment]
子板块是这样的
![Screenshot_20200718-125543](https://user-images.githubusercontent.com/5838634/87845056-1cdd5a00-c8f6-11ea-924a-3d46f6f5e740.png)

**Comment by kidozh** [comment]
你可以使用v2.0的Discuz Hub访问子论坛。经过我们的确认，应该能满足您的正常需要。

Github Release : [https://github.com/kidozh/DiscuzHub/releases/tag/v2.0](https://github.com/kidozh/DiscuzHub/releases/tag/v2.0)


![Screenshot_2020-07-18-13-50-52-036_com kidozh dis](https://user-images.githubusercontent.com/11661760/87845850-d7248f80-c8fd-11ea-8cce-6087fdb5ff83.png)

非常感谢您的建议。

**Comment by kidozh** [comment]
您也可以使用腾讯微云下载APK ：[https://share.weiyun.com/xQvLw5GX](https://share.weiyun.com/xQvLw5GX)

**Comment by onlymash** [comment]
能用了 谢谢

**Comment by kidozh** [comment]
closed.
