### ISSUE TITLE
[new feature]付费主题无法购买

### ISSUE THREAD

**Issue by mzhboy** [kidozh/DiscuzHub#11]
某些帖子需要支付金币之类的才能查看，app没有实现这个功能

**Comment by kidozh** [comment]
您好：

  我们的最新版本是支持购买主题的，在应用最上方有一个价格的显示，如图所示
![Screenshot_2020-12-09-17-28-27-853_com kidozh dis](https://user-images.githubusercontent.com/11661760/101611342-59942400-3a44-11eb-8a66-a1b0411e5a19.jpg)

您可以升级到最新的版本以获得此特征。或者如果你可以提供论坛地址以便我们更好地确定问题所在。（我们目前注意到keylol存在悬赏和购买分不清的问题，这似乎是一个私有的bug，我们暂时不会修复此bug）

感谢你的issue

**Comment by kidozh** [comment]
由于我们上架了Google Play 因此我们无法继续提供直接的下载链接，您可以使用Google Play下载并安装最新的本应用

**Comment by mzhboy** [comment]
已经测试了，问题解决
