### ISSUE TITLE
使用 GitHub Actions 进行构建

### ISSUE THREAD

**Issue by laozhoubuluo** [kidozh/DiscuzHub#13]
考虑到目前贵应用已经支持专属论坛的编译与发布，但目前的流程对于并非具有 Android 应用开发甚至客户端开发经验的站长来说体验未必友好。

一方面源于其对 Android Studio 操作的不熟悉，例如不熟悉如何加载 Maven 镜像等，这可能难以在一段时间内解决。另一方面下载 Android SDK 以及进行 Gradle 构建所需的资源对于未必具有快速网络环境甚至没有使用代理服务器的用户来说难以完成。因此如果能通过 GitHub Actions 进行构建，可以极大的节约站长用于打包 Android 应用所需的时间。

站长只需要按照文档进行简单的定制，并在首次构建时通过互联网工具或者 JDK 生成 keystore 文件 ( 需要通过 base64 编码, 或者使用 GPG 加密并编码为一个字符串 ) 放入 Secret  即可( **这里有潜藏的安全问题，毕竟 GitHub 的安全性未必能承载此数据，具体是否考虑还需要进一步评估** ) 。

通过简单的定制流程后，站点即可直接从 GitHub Actions 获取可运行的安装包。后续更新也可以直接采取反向 merge 上游更改， merge 之后即可获取可运行的更新版本的安装包，可以极大的节约站点定制所需的时间，并降低分支版本碎片化几率。

甚至贵应用本身的构建也可以采用上述流程进行，同样可以节约开发团队发行新版本所占用的时间以及精力。**当然简单的流程带来的用户数的增多，以及随之而来的一系列更复杂的问题也是需要开发者进行考虑的。**

**Comment by kidozh** [comment]
我们会考虑此方案的，目前对于Github actions并不是很熟悉，经过评估后我们会上线此功能的。

非常感谢你的意见。

**Comment by kidozh** [comment]
您好，我们已经发布了一个构建调试类型的github action，其能正常的编译出**debug** 的apk，但是签名可能发生变化，每次更新新版本都需要卸载旧版本的应用。

GitHub action结果：[https://github.com/kidozh/DiscuzHub/actions/runs/547536062](https://github.com/kidozh/DiscuzHub/actions/runs/547536062)

关于加密的这一块，可以考虑让用户fork一个private的库，自行上传一个keystore后使用分发。但是仍然解决不了论坛方需要自行替换图标这一块，我会考虑写一个build的脚本

**Comment by laozhoubuluo** [comment]
> 
> 
> 您好，我们已经发布了一个构建调试类型的github action，其能正常的编译出**debug** 的apk，但是签名可能发生变化，每次更新新版本都需要卸载旧版本的应用。
> 
> GitHub action结果：https://github.com/kidozh/DiscuzHub/actions/runs/547536062
> 
> 关于加密的这一块，可以考虑让用户fork一个private的库，自行上传一个keystore后使用分发。但是仍然解决不了论坛方需要自行替换图标这一块，我会考虑写一个build的脚本

1. 签名变化的话应该就是要正确导入 keystone ，keystone 设置正确之后签名应该就会稳定了。
2. 修改图标的话，可以考虑引导用户自行修改 https://github.com/kidozh/DiscuzHub/blob/master/app/src/main/res/mipmap-xxxhdpi/logo.png 文件吧。

我不是专业 Android 开发，如有说的不到的地方请见谅。

**Comment by kidozh** [comment]
> > 您好，我们已经发布了一个构建调试类型的github action，其能正常的编译出**debug** 的apk，但是签名可能发生变化，每次更新新版本都需要卸载旧版本的应用。
> > GitHub action结果：https://github.com/kidozh/DiscuzHub/actions/runs/547536062
> > 关于加密的这一块，可以考虑让用户fork一个private的库，自行上传一个keystore后使用分发。但是仍然解决不了论坛方需要自行替换图标这一块，我会考虑写一个build的脚本
> 
> 1. 签名变化的话应该就是要正确导入 keystone ，keystone 设置正确之后签名应该就会稳定了。
> 2. 修改图标的话，可以考虑引导用户自行修改 https://github.com/kidozh/DiscuzHub/blob/master/app/src/main/res/mipmap-xxxhdpi/logo.png 文件吧。
> 
> 我不是专业 Android 开发，如有说的不到的地方请见谅。

我们已经成功使用Github action编译出了带正常签名的release版本的apk，见此[https://github.com/kidozh/DiscuzHub/runs/1896890225?check_suite_focus=true](https://github.com/kidozh/DiscuzHub/runs/1896890225?check_suite_focus=true)，我们看一下如何编译专属于单一论坛的脚本，使得Github action能够直接编译出正常的版本

**Comment by kidozh** [comment]
你可以参考[使用Github Action构建专属应用](https://discuzhub.kidozh.com/zh/customize-bbs-in-github/)以使用Github action构建专属论坛版本的应用。
