### ISSUE TITLE
A 版块的「全局置顶」「分类置顶」在其他版块不显示

### ISSUE THREAD

**Issue by KHwang9883** [kidozh/DiscuzHub#14]
例如我设置了一个 A 版块的帖子为「全局置顶」，该帖子不会在 B 版块显示。PC 端和移动网页端正常，DiscuzHub 某个版本更新之后出现此 Bug

**Comment by kidozh** [comment]
我们已经在本地复现了此BUG，正在解决这个问题，如果顺利的话，将随着下一个版本更新此BUG。

**Comment by kidozh** [comment]
我们已经确认了BUG的所在，默认的查询状态值被错误的设置所致，我们已经修复了此bug。

但是一旦设置了高级浏览选项（查看排序、热帖等），遵循网页浏览逻辑，API并不会返回与此板块无关的帖子，因此全局置顶和分类置顶仍然不会显示。

我们会在下一个版本发布更新以修复此bug，预期就在这几天了。

非常感谢你的报告。
