### ISSUE TITLE
点进帖子页，加载失败

### ISSUE THREAD

**Issue by xiaozhinian-g** [kidozh/DiscuzHub#15]
我用 https://github.com/kidozh/DiscuzHub/releases/tag/v4.5 这个安装包试了一下，发现我的网站列表页和其他页面正常，但是只要一点进帖子页面，就振动一下，返回到上一个页面，没有其他错误提示。

有错误日志吗？

**Comment by kidozh** [comment]
我使用该版本对Keylol和MCBBS都进行了浏览，并未出现你说的BUG，此BUG无法在我们的环境中复现。

从我的经验来说，有可能是帖子内容的API返回的内容不对导致的解析失败。振动通常是帖子加载完成或者是错误导致的。错误日志这一块，您如果方便的话，可以接ADB Logcat调试一下发给我们。

不过最方便的还是告诉我们是哪个论坛？我们可以查看到API内容。

**Comment by xiaozhinian-g** [comment]
https://www.guhei.net/forum.php

**Comment by kidozh** [comment]
我们查看了此论坛，发现是API返回的字段中不包含dbdatline，其会导致我们解析出空子段，因此导致的程序崩溃。

我们已经修复了此BUG，你可以使用[Discuz Nightly](https://discuzhub.kidozh.com/zh-hk/nightly-version/)查看并安装最新的版本。在解决方案中，我们采纳了dateline这个备选字段。

然而，应该是论坛魔改所致，所有返回的楼层的内容都是 提示: " *作者被禁止或删除 内容自动屏蔽* "，这应该是某个插件影响所致。dateline这个字段在别的论坛应当是个性化的时间表示（例如X天前），而此论坛返回的却是一个秒的时间戳。这也导致了最终的时间显示错误。

同时我们也发现API返回错误为“您访问的页面无手机页面，是否进一步访问电脑版？继续访问”(mobile_template_no_found)，因此我们合理的推论，论坛开发者可能安装了对于手机页面干扰的模板导致API工作异常。

我们使用虚拟机访问了某个界面，最终如图所示。

![image](https://user-images.githubusercontent.com/11661760/108480262-aeb8a580-72d1-11eb-80de-15206fb2e698.png)

总而言之，根据我们的判断，这应该是一个论坛配置错误出现的错误导致的页面渲染异常。我们建议您可以联系网站管理员解决此问题。

**Comment by xiaozhinian-g** [comment]
> 我们查看了此论坛，发现是API返回的字段中不包含dbdatline，其会导致我们解析出空子段，因此导致的程序崩溃。
> 
> 我们已经修复了此BUG，你可以使用[Discuz Nightly](https://discuzhub.kidozh.com/zh-hk/nightly-version/)查看并安装最新的版本。在解决方案中，我们采纳了dateline这个备选字段。
> 
> 然而，应该是论坛魔改所致，所有返回的楼层的内容都是 提示: " _作者被禁止或删除 内容自动屏蔽_ "，这应该是某个插件影响所致。dateline这个字段在别的论坛应当是个性化的时间表示（例如X天前），而此论坛返回的却是一个秒的时间戳。这也导致了最终的时间显示错误。
> 
> 同时我们也发现API返回错误为“您访问的页面无手机页面，是否进一步访问电脑版？继续访问”(mobile_template_no_found)，因此我们合理的推论，论坛开发者可能安装了对于手机页面干扰的模板导致API工作异常。
> 
> 我们使用虚拟机访问了某个界面，最终如图所示。
> 
> ![图像](https://user-images.githubusercontent.com/11661760/108480262-aeb8a580-72d1-11eb-80de-15206fb2e698.png)
> 
> 总而言之，根据我们的判断，这应该是一个论坛配置错误出现的错误导致的页面渲染异常。我们建议您可以联系网站管理员解决此问题。



thank you

**Comment by kidozh** [comment]
You are welcome and thanks for your issue. It will be closed but you can still reopen it if any progress is updated. Please feel free to contact us if you need further help.

Thanks again for your assistance.

With best wishes,
Discuz Hub

**Comment by kidozh** [comment]
You are welcome and thanks for your issue. It will be closed but you can still reopen it if any progress is updated. Please feel free to contact us if you need further help.

Thanks again for your assistance.

With best wishes,
Discuz Hub
