### ISSUE TITLE
帖子内干扰码

### ISSUE THREAD

**Issue by xiaozhinian-g** [kidozh/DiscuzHub#16]
论坛开启干扰码后，访问帖子，干扰码出现。（网页版是通过设置干扰码颜色和背景一样，所以看不出，APP直接显示了）
![photo_2021-02-21_18-32-33](https://user-images.githubusercontent.com/66472360/108622429-bf088600-7473-11eb-8d26-77af3b790aeb.jpg)

**Comment by kidozh** [comment]
您好

我们已经确定了问题所在，我们会使用正则表达式手动删除`<font class="jammer"></font>`，请问您可以提供一下插件名称吗？我们比较担心的是插件版本更新后，这个关键词会发生变化的情况。

出于兼容性的要求，我们会给用户一个“是否自动消除干扰码”选项。

我们会着手更新此BUG，修复后我们会在此issue通知您。

**Comment by xiaozhinian-g** [comment]
> 您好
> 
> 我们已经确定了问题所在，我们会使用正则表达式手动删除`<font class="jammer"></font>`，请问您可以提供一下插件名称吗？我们比较担心的是插件版本更新后，这个关键词会发生变化的情况。
> 
> 出于兼容性的要求，我们会给用户一个“是否自动消除干扰码”选项。
> 
> 我们会着手更新此BUG，修复后我们会在此issue通知您。

这不是插件，是系统自身的。

不建议删除掉这个，我的建议是和默认行为一样（用css 把干扰码颜色设置和背景一样。）

**Comment by kidozh** [comment]
> > 您好
> > 
> > 我们已经确定了问题所在，我们会使用正则表达式手动删除`<font class="jammer"></font>`，请问您可以提供一下插件名称吗？我们比较担心的是插件版本更新后，这个关键词会发生变化的情况。
> > 
> > 出于兼容性的要求，我们会给用户一个“是否自动消除干扰码”选项。
> > 
> > 我们会着手更新此BUG，修复后我们会在此issue通知您。
> 
> 这不是插件，是系统自身的。
> 
> 不建议删除掉这个，我的建议是和默认行为一样（用css 把干扰码颜色设置和背景一样。）

解析HTML相对来说非常耗时，尤其是涉及到css和js时。出于安全的考量，我们并未解析HTML，而是自己写了个taghandler去处理所有标签信息。我们可以内置一个css样式，但是解析多余的css会造成不必要的性能损失。同时解析富文本也会造成可见的文字图片排版错误。既然我们已经知道了这些信息毫无作用，直接移除干扰码会更方便。

**Comment by kidozh** [comment]
我们已经在[https://github.com/kidozh/DiscuzHub/commit/f020fa7e0ed336bedb4510bd1ca6f9031673d8d3](https://github.com/kidozh/DiscuzHub/commit/f020fa7e0ed336bedb4510bd1ca6f9031673d8d3) 修复了此问题。

请等待我们发布最新版的Discuz Hub，我们会在下一个版本中正式发布包含此修复的安装包
