### ISSUE TITLE
电梯直达与收藏的版块

### ISSUE THREAD

**Issue by mzhboy** [kidozh/DiscuzHub#17]
【电梯直达】很实用，经常遇到非常长的贴，数百楼甚至上千楼，要是能输入楼层跳过去会很快。app没有预取功能，也希望能实现。不过即使有预取功能也没法很好处理长楼~~需要一直划一直划。

【收藏的版块】有的论坛允许显示收藏的版块，这样子版块也可以显示在首页，非常方便。

另外在【探索】页面，希望把内嵌浏览器放到最后，把【收藏帖子】【收藏论坛】提前

**Comment by kidozh** [comment]
电梯直达这一块，我们会加上的，但是会用一个新的界面。

收藏板块这一块，我们会放到主界面和分区板块合并

探索这个，我们也会调整界面的顺序

**Comment by kidozh** [comment]
预取这一块因为不好判定buffer的距离，所以我们默认是要求滑倒最下面才进行操作。我们也可以给一个缓冲判定，但是可能会出现反复请求的情况，所以就没给上这个。我们会考虑加一个开关以预取，但是我们无法承诺此更新

**Comment by mzhboy** [comment]
预取只需要预取当前页的下一页或者下2页就够了吧，只要到了x页面就取x+1页，并不会花多少流量

**Comment by kidozh** [comment]
在[commit](https://github.com/kidozh/DiscuzHub/commit/a95e707c87bf896e0fd8cabf48ac0e1495626f3e)之中，我们已经完成了分页视图的适配并支持电梯直达功能。您可以使用Discuz-nightly获得最新编译的版本。我们会在下个版本发布此更新。

**Comment by kidozh** [comment]
关于预取功能，我们查看了以下最新的Recyclerview的API，发现有关的判定API已失效。因此我们可能无法预取此页，还是要滑倒底部之后才能触发读取下一页的行为。
