### ISSUE TITLE
您可以开发论坛管理功能吗，就是管理进行删帖等操作

### ISSUE THREAD

**Issue by Nakasu-ksm** [kidozh/DiscuzHub#18]
您可以开发论坛管理功能吗，就是管理进行删帖等操作

**Comment by kidozh** [comment]
似乎可能也许大概Discuz没有留这个API诶，应该挺难的，不过也只能做到管理员删帖的这种功能。。。

**Comment by Nakasu-ksm** [comment]
> 似乎可能也许大概Discuz没有留这个API诶，应该挺难的，不过也只能做到管理员删帖的这种功能。。。

是的就是这个功能

**Comment by kidozh** [comment]
@dora-world 我们看一下怎么调用API吧，这个可能问题比较多。。 。

**Comment by kidozh** [comment]
您好，这个api我们找到了，我们正在考虑看看如何实现此功能。您将会在此issue里接收到我们的此次Patch

**Comment by Nakasu-ksm** [comment]
好的感谢

**Comment by kidozh** [comment]
学业繁忙 可能要鸽到下个月去了。。。

**Comment by kidozh** [comment]
我们已经新增了管理论坛模式，在5.2版本正式启用，您在登陆管理员账号后，可以长按帖子或者主题进行管理。

需要指出的是，删除帖子和主题必须填上理由。
