### ISSUE TITLE
需要TID/PID/UID/FID操作

### ISSUE THREAD

**Issue by CaveNightingale** [kidozh/DiscuzHub#19]
目前应用内无任何关于这四种ID的操作支持

然而至少在mcbbs这几个id用的算是比较多的，建议加上

另外建议遇到/thread-xxx-x-x.html的url直接在应用内打开

**Comment by kidozh** [comment]
第一个TID/PID/UID/FID操作指的是什么，是直接跳转到对应的板块上去吗？我们可能需要进一步阐述。

我们目前是支持对于缩略URL的支持的。

我们之前发布了针对MCBBS的应用，但是感觉没什么人用，所以我们也没有继续维护专有应用的计划了。我们会尝试复现此BUG。

**Comment by kidozh** [comment]
要是您需要直接跳转，你是需要先打开至少一个帖子的详细页，然后我们会自动识别缩略形式（因为keylol是f-{fid}-{page}这种形式）。之后我们的应用就可以识别伪静态链接并自动跳转到对应的内置界面了。

**Comment by CaveNightingale** [comment]
> 第一个TID/PID/UID/FID操作指的是什么，是直接跳转到对应的板块上去吗？我们可能需要进一步阐述。
> 
> 我们目前是支持对于缩略URL的支持的。
> 
> 我们之前发布了针对MCBBS的应用，但是感觉没什么人用，所以我们也没有继续维护专有应用的计划了。我们会尝试复现此BUG。

一是直接根据id跳转到对应页面去
二是显示对应页面的id

伪静态的话我目前在登录MCBBS是没有见到有识别伪静态链接

**Comment by kidozh** [comment]
> > 第一个TID/PID/UID/FID操作指的是什么，是直接跳转到对应的板块上去吗？我们可能需要进一步阐述。
> > 
> > 我们目前是支持对于缩略URL的支持的。
> > 
> > 我们之前发布了针对MCBBS的应用，但是感觉没什么人用，所以我们也没有继续维护专有应用的计划了。我们会尝试复现此BUG。
> 
> 一是直接根据id跳转到对应页面去
> 二是显示对应页面的id
> 
> 伪静态的话我目前在登录MCBBS是没有见到有识别伪静态链接


我们能够成功跳转此伪静态链接。

您可以提供具体的链接方便我们调试吗？

![Screenshot_2021-11-07-01-49-25-177_com.kidozh.discuzhub.jpg](https://user-images.githubusercontent.com/11661760/140629243-094c16e6-b228-4721-99fd-4083bd1ea414.jpg)

![Screenshot_2021-11-07-01-49-17-327_com.kidozh.discuzhub.jpg](https://user-images.githubusercontent.com/11661760/140629253-f69539b1-a26d-4c72-ac1e-894e987755bd.jpg)

关于快速跳转这一个，我们会放进waitlist里面的

**Comment by CaveNightingale** [comment]
https://www.mcbbs.net/thread-1273352-1-1.html



你可以去看看这帖里面那个链接



---原始邮件---
发件人: "Kido ***@***.***&gt;
发送时间: 2021年11月7日(周日) 上午9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kidozh/DiscuzHub] 需要TID/PID/UID/FID操作 (Issue #19)




   
第一个TID/PID/UID/FID操作指的是什么，是直接跳转到对应的板块上去吗？我们可能需要进一步阐述。
 
我们目前是支持对于缩略URL的支持的。
 
我们之前发布了针对MCBBS的应用，但是感觉没什么人用，所以我们也没有继续维护专有应用的计划了。我们会尝试复现此BUG。
  
一是直接根据id跳转到对应页面去
 二是显示对应页面的id
 
伪静态的话我目前在登录MCBBS是没有见到有识别伪静态链接
  
我们能够成功跳转此伪静态链接。
 
您可以提供具体的链接方便我们调试吗？
 

 

 
关于快速跳转这一个，我们会放进waitlist里面的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kidozh** [comment]
我们已经在新版本4.10之中加入了快速跳转功能（Shortcut），唯一不支持的是PID，因为这需要查询TID获得，所以暂时没有办法做这个
![image](https://user-images.githubusercontent.com/11661760/143282385-664a96ab-d52c-44cd-9de4-dd7033136393.png)

关于第二个链接无法跳转的问题，应该是一个页面被错误覆盖导致的，我们已经在新版本中设置缓存备份，已经可以正常实现跳转了。

再次感谢您的报告。
