### ISSUE TITLE
帖子内打开超链接/url 存在的问题

### ISSUE THREAD

**Issue by onlymash** [kidozh/DiscuzHub#2]
url 中的 `&` 变成了 `&amp;`，无法打开正确的帖子。
另外应该可以解析 url 的 host，如果与当前论坛一样，直接在应用内打开新帖子，不一样的话再调用浏览器打开。
![Screenshot_20200718-140729](https://user-images.githubusercontent.com/5838634/87846224-ea852a00-c900-11ea-8e4e-6b6a2de67d86.png)
![Screenshot_20200718-140744](https://user-images.githubusercontent.com/5838634/87846227-eeb14780-c900-11ea-96c2-6c5b55ce879f.png)

**Comment by kidozh** [comment]
第一个问题，URL被硬编码这个问题，服务器直接发过来的内容中所有的&都被直接转译为&amps;。这也是为了防止XSS，这是服务器安全策略问题。我们收到了这个被转码的链接，进行正常的跳转。所以导致了这个问题。我晚上回来看看怎么解决这个编码问题。应该是能尽快修复的。

第二个其实很麻烦，因为很多论坛因为缓存和伪静态的原因，自定义了帖子、论坛的链接。我们也不知道应该如何解析这些链接，也根本拿不到应该跳转的帖子或者论坛的编号，比如有的就是f-{fid}-{page}.html（就比如keylol论坛）。我们正在询问DZ官方，到时候看看怎么解决这个伪静态无法跳转的问题。但是应该是能解决这个问题实现正常的跳转功能。

Android 11才引入了动态捕捉URL的方法，我们除非把所有的DZ论坛写死进代码里，要不然很难做到从URL直接接管到应用里然后打开。这个新的功能如果要实现，也只能在最新的Android 11里实现。这块我还没有先例，有可能就把网址焊死在代码里也说不定。

**Comment by kidozh** [comment]
在最新的2.1版本中，我们已经修复了外向链接编码问题，现在DiscuzHub能够正确处理URL并且进行智能的跳转操作。

**Comment by kidozh** [comment]
closed.

**Comment by kidozh** [comment]
建议还是用2.2的版本。2.1当时发布的太仓促很多地方有BUG，在伪静态的页面上跳转有的时候会抽。
https://github.com/kidozh/DiscuzHub/releases/download/v2.2/app-release.apk
