### ISSUE TITLE
怎么把收藏版块给砍了 / 能不能加一个显示评分的功能

### ISSUE THREAD

**Issue by DreamVoid** [kidozh/DiscuzHub#20]
之前版本收藏的版块都会置顶在首页，最新版本就无了，希望可以弄回来
另外希望可以加一个显示每个帖子评分的功能，每次看评分内容都要换浏览器看很不方便。
如果能再弄出一个给予评分就更好了

**Comment by kidozh** [comment]
1. 这应该是一个兼容Android 12，升级了部分组件引发的BUG，我们会在接下来的版本中修复这个BUG。
2. 评分是什么啊，正常的Discuz系统都没有评分这一说吧，有点赞和点踩什么的，但是当时因为部分用户反映用不到，再加上并不是所有的帖子都能被点赞的，因此我们隐藏了这个like和dislike的系统

**Comment by kidozh** [comment]
评分这个东西，似乎Discuz并没有留下调用的接口，因此我们也无能为力，很抱歉

**Comment by kidozh** [comment]
新版已经修复此BUG。

评分目前来说是无法显示的，很抱歉。
