### ISSUE TITLE
有浏览权限的版块不显示；版块列表回复数为 0 的主题帖下出现其他帖子的回帖；管理用户页面左划重新登录会出现两个相同用户

### ISSUE THREAD

**Issue by KHwang9883** [kidozh/DiscuzHub#21]
如图，「谈天说地」下的版块我设置了浏览权限，4.10 版本使用有浏览权限账号登录后该板块不显示，4.9 及更早版本正常
![QQ截图20211202020704](https://user-images.githubusercontent.com/44646371/144289973-7dcaf7be-b3f9-479d-89d4-e40fe104443d.png)
![Screenshot_2021-12-02-02-06-20-980_com kidozh discuzhub](https://user-images.githubusercontent.com/44646371/144289938-f16ec8c1-6ac6-48b7-81a5-8d2eaa550eb9.jpg)

版块列表回复数为 0 的主题帖下出现其他帖子的回帖
![Screenshot_2021-12-02-02-11-13-622_com kidozh discuzhub](https://user-images.githubusercontent.com/44646371/144290093-fdaae51e-9119-4beb-a56c-162847abd646.jpg)

另外管理用户页面，左划重新登录会出现两个相同用户

[论坛地址](https://www.marioforever.net/)，升级过掌上论坛插件

**Comment by kidozh** [comment]
1. 有可能是当时写主页的时候用的是不带cookie的client去访问的，所以导致没有正确显示权限，这点我去看一下怎么办。
2. 第二条有可能是adapter的缓存刷新错误导致的，我看一下怎么强制刷新缓存，避免这个情况。
3. 出现两个重名用户算是老BUG了，一直都没修，下一个版本我看怎么修一下，老疾了属于是。

**Comment by kidozh** [comment]
我们应该已经对这个issue下的所有问题修复完毕了。

1. 是因为我们迁移到Android 12后，由于AsyncTask被弃用，因此我们使用了Thread重新写了整个并发逻辑，导致了实际上已登录账号的cookie并没有正确的储存进数据库中，引发了此BUG
2. 因为我们默认对没有回复的帖子没有做渲染处理，而是缓存了某个列表，导致了误入的情况，我们已经更新了此逻辑
3. 我们现在不再允许一个论坛出现两个同UID的账号，UID相同的账号现在会被覆盖处理。


我们将会在最近发布新的更新，预计将会解决目前的issue内的问题。感谢您的报告。

PS. 目前我们开发的[DiscuzHub for flutter](https://github.com/kidozh/discuz_flutter)可以运行在iOS，Android的手机，平板和一些可折叠设备上，我们预计将会在圣诞节期间发布一个测试版，如果您有兴趣的话，可以体验一下。
