### ISSUE TITLE
主题帖列表拉到底后无限循环

### ISSUE THREAD

**Issue by KHwang9883** [kidozh/DiscuzHub#23]

**Comment by kidozh** [comment]
能举个例子吗，我看着这个很正常

![image](https://user-images.githubusercontent.com/11661760/146580026-3a3e370e-8f34-423f-945d-14a960981698.png)

**Comment by KHwang9883** [comment]
![Screenshot_2021-12-18-00-56-11-406_com kidozh discuzhub](https://user-images.githubusercontent.com/44646371/146580662-cfe4436d-9edb-4836-a431-2af7713ceff0.jpg)
之前版本拉到底时会提示已经加载了所有帖子

**Comment by kidozh** [comment]
对 这个是个BUG，好像是数量和现存的判断不正确导致的，我看看是哪个地方没有判断对的

**Comment by kidozh** [comment]
应该是viewModel的条件被错误判断导致的，我们已经修复此BUG，感谢老哥大半夜的报告。。。晚安

**Comment by KHwang9883** [comment]
似乎并没有完全修复，我论坛的这个版块还是会循环一次，提示已经加载了所有 63 条帖子，但该板块实际只有 39 条
![Screenshot_2021-12-31-07-29-33-266_com kidozh dis](https://user-images.githubusercontent.com/44646371/147794408-63207c5a-d2cd-412b-9e82-997e375d2815.jpg)
![QQ截图20211231072948](https://user-images.githubusercontent.com/44646371/147794412-d2fa50fe-0e61-4d31-a8d1-c23ff8c32dc8.png)

**Comment by kidozh** [comment]
我们已经重现此bug，我们正在查看问题所在

**Comment by kidozh** [comment]
应该是条件判断忘了放=了，所以page越界了。。。
