### ISSUE TITLE
在登录论坛后，通知-系统通知或者通知-帖子列表页面点击后 APP 会闪退

### ISSUE THREAD

**Issue by laozhoubuluo** [kidozh/DiscuzHub#24]
在登录论坛后，通知-系统通知或者通知-帖子列表页面点击后 APP 会闪退。

测试 www.dismall.com 和 www.mcbbs.net 两个网站都有问题，MIUI 提示是因为空指针异常导致闪退，辛苦帮忙排查一下，谢谢。

终端：小米10 / MIUI 12.5.10
Android 版本：11
Android 安全更新版本：2021-10-01
故障位置以及系统报错信息：见下图

**Comment by laozhoubuluo** [comment]
![Screenshot_2021-12-29-20-20-32-815_com miui thirdappassistant](https://user-images.githubusercontent.com/31075951/147665017-dcc282bf-257b-4641-947b-3bb4f8eb528c.jpg)
![Screenshot_2021-12-29-21-01-37-980_com kidozh discuzhub](https://user-images.githubusercontent.com/31075951/147665030-feecda22-1a4c-4f1e-a469-6500e16216a8.jpg)

**Comment by kidozh** [comment]
你说的通知是从通知栏里直接点进去还是界面里的通知直接点进去呢，dismall我没有试，我用的mcbbs和keylol，在界面里面都是正常的，可以正常跳转。![Screenshot_2021-12-29-13-27-00-643_com.kidozh.discuzhub.debug.jpg](https://user-images.githubusercontent.com/11661760/147667196-1009ac84-2fb1-4001-a3ae-f265c55dc332.jpg)![Screenshot_2021-12-29-13-25-21-653_com.kidozh.discuzhub.debug.jpg](https://user-images.githubusercontent.com/11661760/147667207-eda785c8-afa3-478a-a20c-9a937c0e9d58.jpg)

如果是通知栏里面的通知的话，我看实在不行就拿掉算了，因为我准备做一个代理推送的插件，到时候就直接服务器推送到一个代理服务器，然后推送给用户。可能我就直接砍掉刚开始使用worker查询notification这个行为了。

我也是小米10 pro，虽然我刷成了欧版，应该是运行一样的。。。

**Comment by laozhoubuluo** [comment]
> 

直接点系统通知或者帖子列表就会闪退到主页。MCBBS 也是这样。我挂个录屏在楼下吧。

**Comment by laozhoubuluo** [comment]
https://user-images.githubusercontent.com/31075951/147670403-5637c204-cd8e-4453-9134-e0c5958c790c.mp4

**Comment by kidozh** [comment]
这个好诡异啊，我没有出现这个，我再看看是啥回事。。。

**Comment by kidozh** [comment]
我复现了我的帖子的bug，我看看怎么修复

**Comment by kidozh** [comment]
应该是你没有发帖的原因，点到系统的时候，因为Android会默认缓存下一个tab的content，因此没有发帖的BUG就被触发了。

主要是这个API返回的是null对象而不是一个空的数组，引发了此次BUG

我们已经修复了此BUG

**Comment by kidozh** [comment]
新版本已经提交Google Play，已修复此BUG，并且我们合并了两个通知栏的内容
