### ISSUE TITLE
支持dz3.5吗？

### ISSUE THREAD

**Issue by tokpig** [kidozh/DiscuzHub#25]
3.5马上来了，官方已经放了包，，，可以支持吗？

**Comment by kidozh** [comment]
如果长上论坛Mobile插件还能在dz3.5使用就能支持，我们会留心动向的

**Comment by kidozh** [comment]
Closed for no further issue

**Comment by kidozh** [comment]
我们刚刚测试了一下，是支持3.5的，前提是您得打开掌上论坛这个插件。感谢报告。
