### ISSUE TITLE
不能进行发帖和回复

### ISSUE THREAD

**Issue by 15864888648** [kidozh/DiscuzHub#26]
登录的时候验证码会出现加载失败，发帖和回复功能不能用，机型安卓11

**Comment by kidozh** [comment]
请问是否能够提供论坛地址呢以及使用机型呢？我们测试了几个常用的Discuz网站，是可以正常加载的。


## 临时解决方案

您可以暂时使用“使用网页登录”以绕开验证码的问题。

或者从Google Play（[https://play.google.com/store/apps/details?id=com.kidozh.discuz_flutter](https://play.google.com/store/apps/details?id=com.kidozh.discuz_flutter)） 或者App store下载我们基于Flutter设计的谈坛，也许改进了这个问题。

**Comment by chouxiangpai123** [comment]
> 请问我们测试了几个常用的Discuz网站，是可以正常加载的。
> 
> ## 临时解决方案
> 您可以暂时使用“使用网页登录”以绕开验证的代码问题。
> 
> 或者从Google Play（https://play.google.com/store/apps/details?id=com.kidozh.discuz_flutter）或者App store下载我们的问题基于Flutter设计的对话平台，可能会改进了这个。

https://chouxiangpai.ml 麻烦开发者帮我查看下，谢谢

**Comment by chouxiangpai123** [comment]
> 我们测试了几个常用的Discuz网站，是可以正常加载的。
> 
> ## 临时解决方案
> 您可以暂时使用“使用网页登录”以绕开验证的代码问题。
> 
> 或者从 Google Play（https://play.google.com/store/apps/details?id=com.kidozh.discuz_flutter）或者 App store 下载我们的问题基于 Flutter 设计的平台，可能会改进这个。

那个淡坛我也下载了，无法加载主题帖

**Comment by kidozh** [comment]
> > 请问我们测试了几个常用的Discuz网站，是可以正常加载的。
> > ## 临时解决方案
> > 您可以暂时使用“使用网页登录”以绕开验证的代码问题。
> > 或者从Google Play（[https://play.google.com/store/apps/details?id=com.kidozh.discuz_flutter）或者App](https://play.google.com/store/apps/details?id=com.kidozh.discuz_flutter%EF%BC%89%E6%88%96%E8%80%85App) store下载我们的问题基于Flutter设计的对话平台，可能会改进了这个。
> 
> https://chouxiangpai.ml 麻烦开发者帮我查看下，谢谢

在我们这是正常运行的，而且也没有刷出来验证码，您可以提供一下具体详情嘛？

**Comment by gutayou** [comment]
![Screenshot_20220120-075317459](https://user-images.githubusercontent.com/71973092/150237170-76ec8fbb-d1b0-4ef4-a1ee-f0fd809c93ee.jpg)

**Comment by 15864888648** [comment]
> 

![Screenshot_20220120-075317459](https://user-images.githubusercontent.com/71973092/150237228-15ca22a1-a090-4f3d-b5ec-ead4246814d3.jpg)
不能回复，也不能进行发帖

**Comment by kidozh** [comment]
> > 
> 
> 
> 
> ![Screenshot_20220120-075317459](https://user-images.githubusercontent.com/71973092/150237228-15ca22a1-a090-4f3d-b5ec-ead4246814d3.jpg)
> 
> 不能回复，也不能进行发帖

应该是网络问题吧，写得很清楚，会不会是vpn影响了https协议？

**Comment by kidozh** [comment]
Closed for no further reply
