### ISSUE TITLE
点击通知栏通知时无法跳转相应主题帖崩溃

### ISSUE THREAD

**Issue by DreamVoid** [kidozh/DiscuzHub#27]
系统安卓11，软件版本最新
通知就是“xxx回复了您的帖子”
报错不能复制，只有截图，凑合看吧

![Screenshot_20220118-110736_应用商店反馈代理程序.png](https://user-images.githubusercontent.com/45266046/149864158-6d221cb6-b850-4213-81a5-13c47ca7edd7.png)
![Screenshot_20220118-110714_应用商店反馈代理程序.png](https://user-images.githubusercontent.com/45266046/149864171-16b4077c-c096-4c55-b909-d8f285799aa7.png)

**Comment by kidozh** [comment]
应该是哪个地方为空吧，我们正在考虑移除这个通知，因为国内Android ROM一般都限制worker的定时启动（我们也是间隔指定时间做一次轮询发布通知的），因为之后我们会做一个推送插件，因此我们正在考虑移除这个功能，我们正在复现此BUG。

**Comment by kidozh** [comment]
我们会在下一个版本修复此BUG，是有一个备选参数在有一次升级之后我们强制要求给，但是这个worker的API比较老，没有配套升级，所以引发了这个BUG
