### ISSUE TITLE
论坛在其他渠道修改密码后导致程序异常

### ISSUE THREAD

**Issue by laozhoubuluo** [kidozh/DiscuzHub#28]
在论坛在其他渠道修改密码后或者其他情况会导致 Session 失效。程序对 Session 失效没有明显的提示，现象为通知页面点击后 APP 显示无消息，同时论坛操作均提示验证码，但实际操作会因网络异常而失败。

希望能考虑判断修改密码或者其他情况导致 Session 失效的情况，在相关情况下主动弹出提示信息以通知用户重新登录，辛苦帮忙排查一下，谢谢。

终端：小米10 / MIUI 12.5.10
Android 版本：11
Android 安全更新版本：2021-10-01

**Comment by kidozh** [comment]
我们之前做了这个反馈，但是发现偶尔API返回的是错误的cookie，导致了失败。

我们之后开发的谈坛倒是解决了这个问题，但是经常因为网络问题session被清空了。。。

**Comment by kidozh** [comment]
我们会重新加上这个实时检查的part，但是主要偶尔返回的空cookie有的时候会干扰运行。。。

**Comment by laozhoubuluo** [comment]
> 我们之前做了这个反馈，但是发现偶尔API返回的是错误的cookie，导致了失败。
> 
> 我们之后开发的谈坛倒是解决了这个问题，但是经常因为网络问题session被清空了。。。

是否有细节的情况，比如某几个 API 容易失败，我可以想办法定位下，但是如果是完全随机的那可能不是程序问题了就。
另外不确定 Cookie 失效有没有判断方法，可以考虑侧面判断一下再做决定，或者直接区分下网络异常和 Cookie 失效（可能是密码已修改或论坛维护，请重新登录）就行。

**Comment by kidozh** [comment]
> > 我们之前做了这个反馈，但是发现偶尔API返回的是错误的cookie，导致了失败。
> > 我们之后开发的谈坛倒是解决了这个问题，但是经常因为网络问题session被清空了。。。
> 
> 是否有细节的情况，比如某几个 API 容易失败，我可以想办法定位下，但是如果是完全随机的那可能不是程序问题了就。 另外不确定 Cookie 失效有没有判断方法，可以考虑侧面判断一下再做决定，或者直接区分下网络异常和 Cookie 失效（可能是密码已修改或论坛维护，请重新登录）就行。

算是比较早了，应该是在半年前我还在国内的时候，keylol和mcbbs这两个有的时候应该是在通知栏的时候，偶尔会返回一个uid为0的情况。我们判断用户登录与否是直接判断uid和已经登陆的uid是否相等，如果不一样就判断cookie失效。这个时候我们会弹出一个dialog，提示用户重新登陆。这也是我们在写flutter客户端判断失效的方式。但是实际上用户登录并没有失效，用户依然能够正常发帖。

主要是我们维护用户的登陆状态是根据服务器发送回的cookie确定的，我对Android和Flutter的运行底层确实不是很清楚。flutter这边的问题就是访问失败会引发cookie失效。这个问题可以说是偶尔发作，所以当时我们直接就删除了这个实时检验的提示。

我们还在看怎么解决这个问题，可能继续加回来这个实时检查。

**Comment by laozhoubuluo** [comment]
> 

我想确认一下是只有这两个论坛吗？
因为您说的这两个论坛都在测试 X3.5 的早期版本，如果恰好是这两个论坛的话，那可能就需要我们查论坛了。

**Comment by kidozh** [comment]
> > 
> 
> 我想确认一下是只有这两个论坛吗？ 因为您说的这两个论坛都在测试 X3.5 的早期版本，如果恰好是这两个论坛的话，那可能就需要我们查论坛了。

我基本上只看这两个论坛，所以测试也是围绕着这两个论坛进行的。

半年前应该3.5都没发布吧，而且keylol和mcbbs我看后台用的是X3.2，这个关于通知偶尔返回uid为0的情况，我们还没具体测试，只是当时抓包显示uid为0，返回的参数也是null。我最近可能比较忙，我再测试一下。

我也不确定是不是代码的问题，我想着中途cookie失效的情况比较少，再加上当时也在迁移到page 2去，所以索性就不检验用户的合法性了。

我觉得可能不是论坛的问题，因为两个论坛偶尔都能出现这种问题。而且很奇怪的就是，一般都是登陆个两三天出这个问题，哪怕是我再登陆的时候已经指明了cookietime是2592000秒，30天。所以当时就觉得这个问题比较诡异，索性就删了。

但是flutter里面，因为dio经常因为网络问题丢失cookie，我们是每次访问都会检验合法性。因为我在英国，这边链接也不是非常稳定，所以这种丢session的情况比较频繁，但是我基本上在用Android原生逛论坛的时候不会丢session。所以就比较诡异。我也不是搞CS的，所以对这一块确实不是很了解。

**Comment by laozhoubuluo** [comment]
> 

1. 了解了，恰好这两个论坛都是 X3.5 ，所以就很尴尬。
2. 他们用的是 20 年的测试版本，具体后续跟了多少不知道。KEYLOL 好像 20 年之后就没跟过上游，MCBBS 去年也专注于他们的新版论坛规划于是停止了和上游的同步。这个 API 由于历史原因 version 是写死 X3.2 的，X3.5 有个新补丁能返回 truediscuzversion ，但是上述两家应该都没更新。
3. 后续问题了解了，这种玄学问题确实头痛。

**Comment by kidozh** [comment]
哈哈哈，尴尬了，这周我重新把实时检查加回来，看看还有没有这种情况。

flutter上丢session倒是很常见哈哈哈，那应该是dio的锅

**Comment by kidozh** [comment]
fix in latest version
