### ISSUE TITLE
在论坛收到新通知后，通知页面的小红点在查看通知后不会消失，只有重启 APP 才能消失

### ISSUE THREAD

**Issue by laozhoubuluo** [kidozh/DiscuzHub#29]
在论坛收到新通知后，通知页面的小红点在查看通知后不会消失，只有重启 APP 才能消失。

测试 www.dismall.com 有问题，辛苦帮忙排查一下，谢谢。

终端：小米10 / MIUI 12.5.10
Android 版本：11
Android 安全更新版本：2021-10-01
故障位置以及系统报错信息：见下图

**Comment by laozhoubuluo** [comment]
![Screenshot_2022-01-21-08-09-08-200_com kidozh discuzhub](https://user-images.githubusercontent.com/31075951/150456662-b402d451-f6da-4222-b966-8227dd5f79fc.jpg)

**Comment by kidozh** [comment]
啊 这个问题。。。Android回调太多了，我看看怎么解决这个问题。。。

主要是回调问题有点麻烦，我加了上了没有就移除badge的代码，但是动态刷新可能又要回调了。。。

**Comment by kidozh** [comment]
现在可能正常了，主要我两个论坛通知都不多，平常还真的不怎么出现这种情况，orz

**Comment by kidozh** [comment]
b2d19876538b074f48610c4eda02567e3906e953
