### ISSUE TITLE
抽屉的网站Logo图标边缘有阴影不够平滑

### ISSUE THREAD

**Issue by onlymash** [kidozh/DiscuzHub#3]
我这正好也有一个应用使用了materialdrawer，就很正常，区别是用kotlin写的。
大概看了你的代码，看起来没什么毛病，不知道为什么不一样。

![image](https://user-images.githubusercontent.com/5838634/87849890-bf113800-c91e-11ea-8b65-ed53be239aba.png)

**Comment by kidozh** [comment]
会不会是图片加载的问题，我是使用Glide 从Discuz！的默认路径下抓取的，你那个是从网络上获得的图片吗。

应该不是Java的锅吧，kotlin最后也编译成Java代码了。

**Comment by onlymash** [comment]
基本一样 你可以看看
https://github.com/flexbooru/flexbooru/

**Comment by kidozh** [comment]
在个人页面上，之前不平滑的原因是我调用了一个小尺寸的头像，因为太小所以就不平滑。

在论坛选择上，不平滑的原因是图片的长宽尺寸离1：1差的很远，这个问题目前论坛不解决我这边也没方法。

**Comment by onlymash** [comment]
跟比例和大小无关，你先尝试把scaleType设置为centerCrop再说

**Comment by onlymash** [comment]
具体你可以参考一下[这里](https://github.com/flexbooru/flexbooru/blob/master/android/src/main/java/onlymash/flexbooru/app/App.kt)的DrawerImageLoader

**Comment by kidozh** [comment]
我代码里直接设成centerinside了，不过centercrop后的样子有点奇怪。

不过在高版本的Android里面 阴影不平滑还是出现
