### ISSUE TITLE
在个人主页中翻页查看积分将导致返回主页面

### ISSUE THREAD

**Issue by CaveNightingale** [kidozh/DiscuzHub#30]
如视频所示：https://wws.lanzouo.com/iLGmgz94v6f
密码:c1dm

**Comment by CaveNightingale** [comment]
具有相同问题的还有基本状况和好友两个选项卡

**Comment by kidozh** [comment]
能提供一下您访问的是哪个论坛吗，我们好定位问题在哪。

是不是www.mcbbs.net，我好像看过你的帖子？

**Comment by CaveNightingale** [comment]
是的

**Comment by kidozh** [comment]
好的好的 我看看是个什么情况，可能最后这个界面也会有更改。。。感觉没有我们写的flutter界面美观

**Comment by kidozh** [comment]
是一个空值引发的的FC，我们正在修复这个BUG，将在下一个版本修复

**Comment by kidozh** [comment]
![image](https://user-images.githubusercontent.com/11661760/150987655-1c7dc910-ca4b-447b-acbe-6a4f30ca477e.png)

我们已经修复了此BUG，更新了界面。
