### ISSUE TITLE
类似问题在通过网址添加论坛时也会出现

### ISSUE THREAD

**Issue by CaveNightingale** [kidozh/DiscuzHub#31]
比较类似于https://github.com/kidozh/DiscuzHub/issues/30
输入完网址点继续就会直接返回主页面

此外，个人主页中头像似乎不能正常加载

**Comment by kidozh** [comment]
第一个应该是正常的，当我们验证了这个网站符合Discuz Mobile API时，我们就会将其加入到本地数据库之中，这样正常就是会返回主界面，这一点是正常的。之前那个应该是一个FC的bug

第二个，MCBBS可能使用了一些不兼容的方法，个人主页中的固定头像UID默认不给显示，偶尔有的能刷出来，这应该是服务器的限制。

您可以查看这三个头像地址

+ https://www.mcbbs.net/uc_server/avatar.php?uid=1620597&size=small
+ https://www.mcbbs.net/uc_server/avatar.php?uid=1620597
+ https://www.mcbbs.net/uc_server/avatar.php?uid=1620597&size=large

都是返回的一个403的头像，因此我们是没有办法解析的

然而在另一个我们关注的论坛里

+ https://keylol.com/uc_server/avatar.php?uid=505230&size=small
+ https://keylol.com/uc_server/avatar.php?uid=505230
+ https://keylol.com/uc_server/avatar.php?uid=505230&size=large

这些头像信息获取的都是正常的，因此我们认为应该是MCBBS可能对于头像的图片获取做了一定的限制。这并不是一个通用的Discuz规则，因此我们没有办法加入对于MCBBS的头像兼容支持。

MCBBS还有个诡异的问题就是，这些链接有时刷的出来，有的时候刷不出来，这个问题我们一直没有能够稳定的复现，所以我们也没有办法修复这个问题。很抱歉。

**Comment by CaveNightingale** [comment]
注意到https://keylol.com/uc_server/data/avatar/000/30/90/28_avatar_big.jpg
https://www.mcbbs.net/uc_server/data/avatar/002/85/37/76_avatar_big.jpg
都是可以正常获取到头像的，为什么不用这个API呢？

**Comment by CaveNightingale** [comment]
另外，返回主页面实在输入错误的时候会返回，而不是提示输入错误，我认为不太友好

**Comment by kidozh** [comment]
> 注意到https://keylol.com/uc_server/data/avatar/000/30/90/28_avatar_big.jpg https://www.mcbbs.net/uc_server/data/avatar/002/85/37/76_avatar_big.jpg 都是可以正常获取到头像的，为什么不用这个API呢？

这个是静态文件，需要用API读取的，但是MCBBS并没有跳转到一个正确的网址上，而是给了个403，所以我们没有办法获取。

而且静态文件生成没有规律，我们也没有办法通过用户id联想到这个静态文件上

**Comment by kidozh** [comment]
> 另外，返回主页面实在输入错误的时候会返回，而不是提示输入错误，我认为不太友好

这是一个FC的BUG，是因为用户输入的URL可能存在一定的错误导致的，我们已经加入了检测的模块以确保正确的URL已经被校验。

我们在下个版本就会修复这个错误。

**Comment by CaveNightingale** [comment]
> > 注意到https://keylol.com/uc_server/data/avatar/000/30/90/28_avatar_big.jpg https://www.mcbbs.net/uc_server/data/avatar/002/85/37/76_avatar_big.jpg 都是可以正常获取到头像的，为什么不用这个API呢？
> 
> 这个是静态文件，需要用API读取的，但是MCBBS并没有跳转到一个正确的网址上，而是给了个403，所以我们没有办法获取。
> 
> 而且静态文件生成没有规律，我们也没有办法通过用户id联想到这个静态文件上

这多半不是一个静态文件，而是个API，据我所知MCBBS的静态文件都在attachment.mcbbs.net上的
然后这个URL和用户id的关系是明显的，也是隔壁mcbbs-wiki用于获取头像的url，类似于这样（我不会写kt，这是java）。
```java
String getAvatarUrl(String bbsurl, int uid){
    return String.format("%s/uc_server/data/avatar/%03d/%02d/%02d/%02d_avatar_big.jpg", bbsurl, uid / 1000000, uid / 10000 % 100, uid / 100 % 100, uid % 100);
}
```

**Comment by CaveNightingale** [comment]
另外，MCBBS去年8月调整过头像机制，用户只允许设置大头像，而不是默认的可以设置大中小三个头像，如果你去查询中头像、小头像，则都找不到头像（老用户除外）

你现在使用那个API印象中应该就是那次调整的时候坏掉的，我之前在MCBBS反馈版提过，但是管理员说那玩意不维护了

**Comment by kidozh** [comment]
歪日，感谢报告，我查看一下其他论坛的缓存政策是不是也是这个，如果是的话，直接命中缓存文件可能会更好一些。

主要是之前有用户反馈avatar有点消耗流量，所以我们没有默认加载big，我们会查看一下这个缓存政策，如果都是一样的缓存政策的话，我们就会修复这个兼容性BUG。

非常感谢~~~

> > > 注意到https://keylol.com/uc_server/data/avatar/000/30/90/28_avatar_big.jpg https://www.mcbbs.net/uc_server/data/avatar/002/85/37/76_avatar_big.jpg 都是可以正常获取到头像的，为什么不用这个API呢？
> > 
> > 
> > 这个是静态文件，需要用API读取的，但是MCBBS并没有跳转到一个正确的网址上，而是给了个403，所以我们没有办法获取。
> > 而且静态文件生成没有规律，我们也没有办法通过用户id联想到这个静态文件上
> 
> 这多半不是一个静态文件，而是个API，据我所知MCBBS的静态文件都在attachment.mcbbs.net上的 然后这个URL和用户id的关系是明显的，也是隔壁mcbbs-wiki用于获取头像的url，类似于这样（我不会写kt，这是java）。
> 
> ```java
> String getAvatarUrl(String bbsurl, int uid){
>     return String.format("%s/uc_server/data/avatar/%03d/%02d/%02d/%02d_avatar_big.jpg", bbsurl, uid / 1000000, uid / 10000 % 100, uid / 100 % 100, uid % 100);
> }
> ```

**Comment by kidozh** [comment]
可以 老哥稳 我们已经迁移到新的头像URL了，下一个版本我们就会修复这个问题

最近因为我们在看怎么做消息推送的事情，所以发版速度可能会延误一会。。。

**Comment by CaveNightingale** [comment]
抱歉，我犯了个错误，mcbbs头像改制后的ucenter头像存储地址应该是attachment.mcbbs.net而不是www.mcbbs.net，通过www.mcbbs.net查到的是头像改制前用户设置的头像

**Comment by CaveNightingale** [comment]
我又去看了一下你说的那个API，虽然管理员说不维护了，但其实后来还是修了的，大概是因为v3的原因（
只不过你用错了
应该是


https://www.mcbbs.net/uc_server/avatar.php?uid=2853776&size=big
https://www.mcbbs.net/uc_server/avatar.php?uid=2853776&size=middle
https://www.mcbbs.net/uc_server/avatar.php?uid=2853776&size=small

是size=big而不是size=large，而且size=middle不可省略

你给那个人的小头像链接解析到403.png的原因只是因为那个人的头像被管理员屏蔽了（从桌面版网页可以看出来是被屏蔽了），而不是这个API本身的故障

（这个API解析出来中头像和小头像是按比例缩小的大头像）

**Comment by kidozh** [comment]
歪日 我们已经更新到新的缓存上去了，今天才开始维护这个情况，其实小头像主要渲染的比较快，也比较省流量，我们再看看要不要切回去老版本。之前我们确实是按照情景加载大中小的。不过我们也有缓存机制，加载一次就不会重复向服务器请求消息了，倒也不是啥答问题，我mark一个improvement

**Comment by kidozh** [comment]
先不按照情景修复 直接统一加载大图把。。。
