### ISSUE TITLE
特殊贴、特殊版块空内容导致程序异常

### ISSUE THREAD

**Issue by laozhoubuluo** [kidozh/DiscuzHub#32]
Discuz! X 由于功能设计因素存在一些特殊贴和特殊板块，例如允许空内容的投票贴以及板块地址重定向的设计，这些设计可能并不和标准应用兼容，导致应用操作异常。

发现的特殊贴：https://www.dismall.com/thread-11453-1-1.html （空内容的投票贴会直接闪回到首页）
发现的特殊板块：https://www.dismall.com/forum-46-1.html （内容重定向会直接闪回到首页）

希望能考虑上述情况导致的异常，至少不以闪回到首页方式处理，谢谢。

终端：小米10 / MIUI 12.5.10
Android 版本：11
Android 安全更新版本：2021-10-01
视频信息见下方补充。

**Comment by laozhoubuluo** [comment]
Discuz! X 这块确实坑，又没有文档，辛苦您了。

**Comment by laozhoubuluo** [comment]
https://user-images.githubusercontent.com/31075951/151661364-dafd70b4-295a-48f1-9583-156845a3bc98.mp4

**Comment by kidozh** [comment]
第一个应该是好办的，这个只需要Jackson给一个default Value就可以，我看一下返回的JSON是一个啥样的

第二个重定向的这个不知道我查看一下返回的JSON是个啥格式。。。

**Comment by kidozh** [comment]
第二个返回的JSON似乎不是一个标准格式，我看看怎么兼容解析

GET https://www.dismall.com/api/mobile/index.php?version=4&module=forumdisplay&fid=46

```json
{
	"Version": "4",
	"Charset": "UTF-8",
	"Variables": {
		"cookiepre": "l9gQ_2132_",
		"auth": "e58aDRhX7UItln0r1B7DiIU\/p+8Ij43\/1bkJDlXftuP4cxEvKN8qbTbENV6LNMN3GaGpzUWgwMO5smoRbnF9REqRlw",
		"saltkey": "HVl8pLad",
		"member_uid": "0",
		"member_username": "",
		"member_avatar": "https:\/\/www.dismall.com\/uc_server\/avatar.php?uid=0&size=small&t=1643460845",
		"groupid": "7",
		"formhash": "3757ee83",
		"ismoderator": "0",
		"readaccess": "1",
		"notice": {
			"newpush": "0",
			"newpm": "0",
			"newprompt": "0",
			"newmypost": "0"
		},
		"forum": {
			"fid": "46",
			"redirect": "https:\/\/addon.dismall.com\/service.html"
		}
	}
}
```

**Comment by kidozh** [comment]
投票界面好像是因为我们的解析问题全部不显示了我们还在排查bug。。。另一个应用就没事。。。![Screenshot_2022-01-29-14-39-31-533_com.kidozh.discuz_flutter.jpg](https://user-images.githubusercontent.com/11661760/151665149-f87cced4-44ab-4962-9c10-9eb40447b5ed.jpg)

**Comment by kidozh** [comment]
现在好像是所有的投票贴都不显示，这个BUG很玄学，搞了好几天一直排查不出来原因，一直不解析special_poll这个字段

**Comment by kidozh** [comment]
第一个BUG已经解决了，应该是嵌套太多层导致的Jackson直接不解析结果了，而且这个感觉应该是Jackson升级引发的

![image](https://user-images.githubusercontent.com/11661760/152385438-51d01ea7-1e68-44a0-b424-9243ffef6a7b.png)

现在能够正确的解析了，但是也有很多问题，我们还在测试，看看是个什么情况

**Comment by kidozh** [comment]
应该是也能正常重定向了，到时候会使用外部浏览器打开这个界面，如果URL合法的话
