### ISSUE TITLE
希望增加 自动检测更新，首页启动图，以及帖子缩略图

### ISSUE THREAD

**Issue by wlhost** [kidozh/DiscuzHub#33]
希望增加 自动检测更新，首页启动图，以及帖子缩略图，底部导航栏个人中心 等

**Comment by kidozh** [comment]
新年快乐🎆

第一个自动更新的问题，因为我们现在还没有架服务器（缺钱懒维护），所以并不打算做这个，跟着google play/华为应用商店海外版更新就行。可能之后我们出消息事时推送服务之后会更新的，只能说也许。。。

第二个，首页启动图不知道说的是什么，如果是splash screen的话，我们是带的，但是国内rom厂商普遍为了广告位阉割了splash screen所以我们也没有办法展示，特色国产rom的feature了属于是

第三个，不知道你说的缩略图是什么意思，如果说的是帖子的摘要的话，很抱歉因为api的原因，discuz并没有提供这个api，所以我们也没有办法做摘要。

第四个，底部导航栏个人中心这个我们不是很理解，主页的底部已经是首页，看板，消息了，这个应该是个人中心的范畴了，您可以描述的更加具体一些吗？


感谢您的来信，祝您春节快乐，虎虎生威🎆
