### ISSUE TITLE
iPad上一个登录bug

### ISSUE THREAD

**Issue by tokpig** [kidozh/DiscuzHub#34]
如果论坛开启验证码登录，会提示登录失败，关闭验证码后可以正常登录
discuz为3.4 最新正式版
验证码正常显示
Android未测试
测试版本为谈坛iPad目前最新版本

**Comment by tokpig** [comment]
iPhone上也是一样的，刚才测试了

**Comment by kidozh** [comment]
这个是Discuz_flutter那个仓库的问题。其实放到那个库里面提issue也是可以的，不过这小事。

我们实际上是提交了一个新的版本修复了这个验证码的bug的，但是因为Apple的审核问题，所以一直没能过。如图所示。


![image](https://user-images.githubusercontent.com/11661760/161439468-2a19eab3-74ec-46af-8584-14af9e87a6a5.png)

![image](https://user-images.githubusercontent.com/11661760/161439486-73f7e1ed-bf35-429d-870d-0b4eadf4f08e.png)


我们还在和Apple沟通怎么解决这些问题。Apple这个审核回复是真的慢有一说一。。。

**Comment by kidozh** [comment]
谈坛的仓库在这里https://github.com/kidozh/discuz_flutter

**Comment by kidozh** [comment]
可能是这个问题https://github.com/kidozh/discuz_flutter/issues/2
