### ISSUE TITLE
http域名首页不能正常显示问题

### ISSUE THREAD

**Issue by haliang0409-cmd** [kidozh/DiscuzHub#36]

**Comment by haliang0409-cmd** [comment]
首页显示net::ERR_CLEARTEXT_NOT_PERMITTED，别的功能正常
原因可能是从Android 9.0 API级别28 开始，默认情况下禁用明文支持
个人建议的解决方案为：
   在manifest 中application节点添加
   android:usesCleartextTraffic="true"

**Comment by kidozh** [comment]
这个功能在旧版本我们是保留的，同时我们也支持解析不正确的HTTPS协议，但是我们还是觉得有点危险，鉴于目前大多数论坛都有SSL证书，所以我们并没有重新允许HTTP协议。

您可以联系论坛管理方添加SSL证书，letsencrypt就是免费的。

非常感谢您的issue。
