### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [kidozh/DiscuzHub#37]
请问是否可以将应用发布到 F-Droid？

**Comment by kidozh** [comment]
精力比较有限，我们精力目前还放在Google play上，您可以通过apkmirror获得更新。我们目前来说一直在开发谈坛，所以版本更新可以预期的很慢。

**Comment by linsui** [comment]
我可以帮助打包提交，更新是自动的。谈坛没有许可证，如果之后开源，我也可以帮助打包提交。

**Comment by kidozh** [comment]
都是开源的，但是问题是为了和google play一致，你需要拿到开发者签名的，这个我不太可能给出来的，所以你也很难打包，你也可以根据mit协议二次分发discuz hub或者谈坛。但是可能咱们的package id就不一样了。

**Comment by linsui** [comment]
F-Droid 一般使用自己的密钥签名。因为应用使用了 firebase，不是开源库，我需要打补丁所以没办法可重现构建。给应用 ID 加个后缀可以吗，这样两个版本不会相互冲突。

**Comment by kidozh** [comment]
算了，我晚些时候上传一个吧，上传了给你更新消息

**Comment by linsui** [comment]
F-Droid 的应用是从源码构建的，如果想要用相同的签名就只能可重现构建。

**Comment by kidozh** [comment]
好像很复杂的样子 你要打后缀就打把，根据MIT协议就行。

**Comment by linsui** [comment]
好的，我准备好构建清单给你看一下。

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11551 你看看有没有问题。APK 用着没问题。请问我可以在这个仓库添加 fastlane 元数据吗？F-Droid 可以从这里抓取应用描述。

**Comment by kidozh** [comment]
没事，应该对安全没有什么影响的吧。我对这个fastlane数据不是很清楚，你要添加发PR过来就行

**Comment by linsui** [comment]
我把 Firebase 推送服务去掉了，这个不是开源的所以 F-Droid 不允许。其他没有变化。我稍后发个 PR 。谢谢！

**Comment by kidozh** [comment]
好的，但是我不确定移除FCM还能不能保证正常运行，这个得看看。如果不行得话，可以使用我们上一个版本的，当时没有引入FCM，所以应该是可以正常运行的

**Comment by linsui** [comment]
我测试了一下浏览论坛是没问题的。https://gitlab.com/linsui/fdroiddata/-/jobs/2876200122/artifacts/download 你可以测试一下 CI 构建的 apk。

**Comment by kidozh** [comment]
我的Pixel 6 Pro是没有办法直接安装这个的，但是Github action是可以的。我不确定是什么问题

**Comment by kidozh** [comment]
如图![Screenshot_20220813-160450.png](https://user-images.githubusercontent.com/11661760/184499822-03d1f013-645d-4281-bcd4-308ee0f8808a.png)

**Comment by linsui** [comment]
这个文件没有签名，要自己签名一下。

**Comment by kidozh** [comment]
这样子，那就不是很清楚了，如果你运行可以那就没问题。

**Comment by linsui** [comment]
我之后会再测试一下，功能应该没有问题。

**Comment by linsui** [comment]
MR 已经合并了，大概两三天内会进入 F-Droid 的存储库。感谢帮助！
