### ISSUE TITLE
关于浏览记录和本地收藏的两点建议

### ISSUE THREAD

**Issue by onlymash** [kidozh/DiscuzHub#4]
1. 浏览记录插入数据库时应当替换已存在的同一帖子的记录，以便刷新时间顺序。
2. 添加一个本地收藏选项，将经常浏览的帖子或板块显示在主页面，方便查看。

**Comment by onlymash** [comment]
还有个bug，滑动删除浏览记录时会FC

**Comment by kidozh** [comment]
1. 刷新时间顺序也可以，应该一会就修正一下，判断tid应该是可以的
2. 第二个我准备把第二个探索页面改成viewpager支持收藏、热帖和论坛推荐的热门论坛
3. 好像是论坛没有给avatar的URL的问题，我回头把相关代码注释一下NotNull，可能升级数据库之后，历史记录有可能被清除。。。我看看怎么迁移会比较好一些

**Comment by kidozh** [comment]
这个branch我已经添加上收藏帖子和的功能（这个可以和论坛服务器同步）

收藏板块因为API提供的formhash不一致的原因目前一直报错，默认只能走本地收藏
