### ISSUE TITLE
好像并不能查看某个用户发的主题贴？

### ISSUE THREAD

**Issue by byebvip** [kidozh/DiscuzHub#40]
![Screenshot_2022-12-04-03-28-50-56_ad0ee1cec2d3831c0d07e43b1bbc4195](https://user-images.githubusercontent.com/23015915/205458464-031ccc54-d4a2-4f61-bd6f-bed9a186ce59.jpg)

它是无法被点击的？

**Comment by kidozh** [comment]
这个就是无法点击的。。。发自我的 iPhone在 2022年12月3日，19:30，byebvip ***@***.***> 写道：﻿

它是无法被点击的？

**Comment by byebvip** [comment]
> 这个就是无法点击的。。。发自我的 iPhone在 2022年12月3日，19:30，byebvip ***@***.***> 写道：﻿ 它是无法被点击的？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

那就是没办法看用户主题贴吗？好像通过uid应该是可以抓到该用户主题帖的吧

**Comment by kidozh** [comment]
这个就没有办法点击，你可以使用谈坛，然后点击帖子计数就能看到这个人发的所有帖子，第一个就是最新的帖子

**Comment by byebvip** [comment]
> 

试了下，谈坛又不能复制帖子内容，哎

**Comment by kidozh** [comment]
> > 
> 
> 
> 
> 试了下，谈坛又不能复制帖子内容，哎

这个确实是没有啥办法，discuzhub开发的比较早，很多布局都钉死了，所以我们另起炉灶选择了谈坛项目，你要是想复制帖子的话，我们可以看看咋弄一个出来。。。

**Comment by kidozh** [comment]
> > 
> 
> 
> 
> 试了下，谈坛又不能复制帖子内容，哎

或者你这样，你可以在谈坛里帖子内容的右上角有一个在网页中打开，直接跳转到内置的页面，然后应该是可以复制内容了的。

**Comment by byebvip** [comment]
> > > 
> > 
> > 
> > 试了下，谈坛又不能复制帖子内容，哎
> 
> 或者你这样，你可以在谈坛里帖子内容的右上角有一个在网页中打开，直接跳转到内置的页面，然后应该是可以复制内容了的。
额.或多或少有点儿不尽人意...
