### ISSUE TITLE
部分论坛后台开启了插件但无法连接

### ISSUE THREAD

**Issue by laozhoubuluo** [kidozh/DiscuzHub#42]
如 https://www.dismall.com/ ，论坛 api/mobile/index.php?version=4&module=check 接口正常但无法识别论坛。

论坛版本为 X3.5 20221231

**Comment by kidozh** [comment]
在埃及，后天回曼城康康，应该是解析内容错误

**Comment by laozhoubuluo** [comment]
> 

辛苦~

**Comment by kidozh** [comment]
应该是因为3.5新增了一个truediscuzversion字段导致的问题，我们已经暂时忽略了这个字段已修复此BUG。

在issue里面我想询问一下，3.5这个字段有啥具体含义吗？

**Comment by kidozh** [comment]
似乎官方dismall论坛里的的discuzcode这个问题也没有解决哈哈哈

https://gitee.com/Discuz/DiscuzX/issues/I67QWG#note_15422630

**Comment by laozhoubuluo** [comment]
> 应该是因为3.5新增了一个truediscuzversion字段导致的问题，我们已经暂时忽略了这个字段已修复此BUG。
> 
> 在issue里面我想询问一下，3.5这个字段有啥具体含义吗？

根据 https://gitee.com/Discuz/DiscuzX/pulls/441 ，由于微社区（2020年4月还活着，但现在凉了）依赖 discuzversion == X3.2, 且微社区平台代码无法修改, 因此在 X3.5 使用 truediscuzversion 标示正确的 Discuz! Version 。
另外正常来说 JSON 新增结构是不应该影响数据读取的，这个写的有点死了。感觉每个 Jackson 都需要能适配新增结构的情况。

**Comment by laozhoubuluo** [comment]
> 似乎官方dismall论坛里的的discuzcode这个问题也没有解决哈哈哈
> 
> https://gitee.com/Discuz/DiscuzX/issues/I67QWG#note_15422630

这个我去反馈一下，官方社区那边有定制化所以升版本没那么积极，不过这两个问题单独改一下问题不大。

**Comment by laozhoubuluo** [comment]
> 应该是因为3.5新增了一个truediscuzversion字段导致的问题，我们已经暂时忽略了这个字段已修复此BUG。
> 
> 在issue里面我想询问一下，3.5这个字段有啥具体含义吗？

我刚才找了一下我熟悉 Java 和 Android 的朋友（毕竟我 Java 就是大一拿个优的水平，也几乎没正经搞过这块儿）。JSON 添加对象可能会影响到完全面向对象的实现，后续我这块儿会尽量减少对已有数据结构的修改。

**Comment by kidozh** [comment]
> > 应该是因为3.5新增了一个truediscuzversion字段导致的问题，我们已经暂时忽略了这个字段已修复此BUG。
> > 在issue里面我想询问一下，3.5这个字段有啥具体含义吗？
> 
> 根据 https://gitee.com/Discuz/DiscuzX/pulls/441 ，由于微社区（2020年4月还活着，但现在凉了）依赖 discuzversion == X3.2, 且微社区平台代码无法修改, 因此在 X3.5 使用 truediscuzversion 标示正确的 Discuz! Version 。 另外正常来说 JSON 新增结构是不应该影响数据读取的，这个写的有点死了。感觉每个 Jackson 都需要能适配新增结构的情况。

主要是有些字段返回的类型都不一样，我记得就是forumdisplay这个，自定义字段没有定义的时候，返回的是字符串，但是一旦定义了，返回的就是一个list，经常因为类型的问题导致转换失败报错，所以我们确实是忽略了所有我们没有列出的字段，但是当时我看着各家的check返回结果都是一样的，所以没有加上这条规则。Jackson如果适配新加的话，有的时候就会因为类型问题报错，所以我们不解析除了我们列出的所有字段外的一些字段。

**Comment by kidozh** [comment]
> > 应该是因为3.5新增了一个truediscuzversion字段导致的问题，我们已经暂时忽略了这个字段已修复此BUG。
> > 在issue里面我想询问一下，3.5这个字段有啥具体含义吗？
> 
> 我刚才找了一下我熟悉 Java 和 Android 的朋友（毕竟我 Java 就是大一拿个优的水平，也几乎没正经搞过这块儿）。JSON 添加对象可能会影响到完全面向对象的实现，后续我这块儿会尽量减少对已有数据结构的修改。

我Java纯粹没怎么好好看，我老python选手了。现在JSON新增字段应该是不会影响的，我们的Jackson全部都加上了省略未列出字段的语法糖，所以应该是不会解析新字段。

主要是我看keylol还是3.4，所以对3.5目前没有仔细地看适配，目前好像就只有我在gitee提的俩问题。

PS. 推送插件这一块已经写好了，差不多年后就扔上去开始测试了。

https://dhp.kidozh.com/

**Comment by laozhoubuluo** [comment]
> > > 应该是因为3.5新增了一个truediscuzversion字段导致的问题，我们已经暂时忽略了这个字段已修复此BUG。
> > > 在issue里面我想询问一下，3.5这个字段有啥具体含义吗？
> > 
> > 
> > 根据 https://gitee.com/Discuz/DiscuzX/pulls/441 ，由于微社区（2020年4月还活着，但现在凉了）依赖 discuzversion == X3.2, 且微社区平台代码无法修改, 因此在 X3.5 使用 truediscuzversion 标示正确的 Discuz! Version 。 另外正常来说 JSON 新增结构是不应该影响数据读取的，这个写的有点死了。感觉每个 Jackson 都需要能适配新增结构的情况。
> 
> 主要是有些字段返回的类型都不一样，我记得就是forumdisplay这个，自定义字段没有定义的时候，返回的是字符串，但是一旦定义了，返回的就是一个list，经常因为类型的问题导致转换失败报错，所以我们确实是忽略了所有我们没有列出的字段，但是当时我看着各家的check返回结果都是一样的，所以没有加上这条规则。Jackson如果适配新加的话，有的时候就会因为类型问题报错，所以我们不解析除了我们列出的所有字段外的一些字段。

是的，这是因为 PHP 弱类型特性以及开发人员不重视类型系统（甚至可以说是反规范，比如数组下标 99% 的程序都是 [0] ，Discuz! 就非要写个 {0} 彰显一下特立独行）导致的。这种问题在 PHP 8 上全部抛异常，我们连人工带软件扫描改了几百个文件，现在还零星的有这种问题报上来，我们头疼的要死。

**Comment by laozhoubuluo** [comment]
> > > 应该是因为3.5新增了一个truediscuzversion字段导致的问题，我们已经暂时忽略了这个字段已修复此BUG。
> > > 在issue里面我想询问一下，3.5这个字段有啥具体含义吗？
> > 
> > 
> > 我刚才找了一下我熟悉 Java 和 Android 的朋友（毕竟我 Java 就是大一拿个优的水平，也几乎没正经搞过这块儿）。JSON 添加对象可能会影响到完全面向对象的实现，后续我这块儿会尽量减少对已有数据结构的修改。
> 
> 我Java纯粹没怎么好好看，我老python选手了。现在JSON新增字段应该是不会影响的，我们的Jackson全部都加上了省略未列出字段的语法糖，所以应该是不会解析新字段。
> 
> 主要是我看keylol还是3.4，所以对3.5目前没有仔细地看适配，目前好像就只有我在gitee提的俩问题。
> 
> PS. 推送插件这一块已经写好了，差不多年后就扔上去开始测试了。
> 
> https://dhp.kidozh.com/

KEYLOL 在 2021 年之后应该就没有完整的跟进我们的更新了，而且 Git 版本也停止了更新，可能考虑自己分支维护了，详见 https://gitee.com/stackia/DiscuzX 。
X3.5 对 API 这块增减字段主要就是这个，别的应该也没啥，毕竟同版本 API 要保持兼容性。新 API 的天坑还不知道啥时候能填上，这个 API 适配难度确实也大，见谅。
推送插件好评，估计能解决不少站点对于手机端的需求了。另外改 mobile 插件的事情确实见谅，猴哥说影响兼容性不愿意改我们别人也没办法，给您添麻烦了。

**Comment by laozhoubuluo** [comment]
> 似乎官方dismall论坛里的的discuzcode这个问题也没有解决哈哈哈
> 
> https://gitee.com/Discuz/DiscuzX/issues/I67QWG#note_15422630

应用中心反馈说补丁打上了，我重新打开了 Issue ，方便补充一下测试么？

**Comment by laozhoubuluo** [comment]
另外还有个问题，我们找了个 X3.5 Release 20221231 的测试站点 https://www.kuozhan.net/api/mobile/index.php?version=4&module=check ，这个网站直接改成 discuzversion 去掉了新增的元素，在 https://discuzhub.kidozh.com/zh/test-my-bbs/ 下测试依然不行。

**Comment by kidozh** [comment]
> > > > 应该是因为3.5新增了一个truediscuzversion字段导致的问题，我们已经暂时忽略了这个字段已修复此BUG。
> > > > 在issue里面我想询问一下，3.5这个字段有啥具体含义吗？
> > > 
> > > 
> > > 我刚才找了一下我熟悉 Java 和 Android 的朋友（毕竟我 Java 就是大一拿个优的水平，也几乎没正经搞过这块儿）。JSON 添加对象可能会影响到完全面向对象的实现，后续我这块儿会尽量减少对已有数据结构的修改。
> > 
> > 
> > 我Java纯粹没怎么好好看，我老python选手了。现在JSON新增字段应该是不会影响的，我们的Jackson全部都加上了省略未列出字段的语法糖，所以应该是不会解析新字段。
> > 主要是我看keylol还是3.4，所以对3.5目前没有仔细地看适配，目前好像就只有我在gitee提的俩问题。
> > PS. 推送插件这一块已经写好了，差不多年后就扔上去开始测试了。
> > https://dhp.kidozh.com/
> 
> KEYLOL 在 2021 年之后应该就没有完整的跟进我们的更新了，而且 Git 版本也停止了更新，可能考虑自己分支维护了，详见 https://gitee.com/stackia/DiscuzX 。 X3.5 对 API 这块增减字段主要就是这个，别的应该也没啥，毕竟同版本 API 要保持兼容性。新 API 的天坑还不知道啥时候能填上，这个 API 适配难度确实也大，见谅。 推送插件好评，估计能解决不少站点对于手机端的需求了。另外改 mobile 插件的事情确实见谅，猴哥说影响兼容性不愿意改我们别人也没办法，给您添麻烦了。

这个问题也不是特别大，留一个修改方法看看安装推送插件的人愿不愿意修改就行，新API这块我也不知道咋办，先优化一下目前推送插件看看。主要是跟随大版本更新我感觉可能来不及，不过现在还没到要修改这里的时候，可以到时候看看

**Comment by kidozh** [comment]
> > 似乎官方dismall论坛里的的discuzcode这个问题也没有解决哈哈哈
> > https://gitee.com/Discuz/DiscuzX/issues/I67QWG#note_15422630
> 
> 应用中心反馈说补丁打上了，我重新打开了 Issue ，方便补充一下测试么？

还是没有，dismall和新站上还是在报mobile_template_not_found，如图所示：


![Screenshot_1673946447](https://user-images.githubusercontent.com/11661760/212855752-6017585d-52a1-4f31-8084-2b9ea0675853.png)

在Discuz Hub上也是一样的，应该是还有一个地方出了问题，可能还是discuzcode这个函数的钩子问题

**Comment by kidozh** [comment]
> 另外还有个问题，我们找了个 X3.5 Release 20221231 的测试站点 https://www.kuozhan.net/api/mobile/index.php?version=4&module=check ，这个网站直接改成 discuzversion 去掉了新增的元素，在 https://discuzhub.kidozh.com/zh/test-my-bbs/ 下测试依然不行。

这个界面因为Redirect anywhere不再允许随意CORS的问题，禁止了我们任意重定向，因此这个界面都不能用了，我到时候会把这个界面重定向到dhp上（因为discuzhub.kidozh.com都是静态文件生成的），然后应该就可以了。

我这边用应用检测都是没问题的。但是帖子界面还是报上一个帖子的问题

**Comment by laozhoubuluo** [comment]
> > > 似乎官方dismall论坛里的的discuzcode这个问题也没有解决哈哈哈
> > > https://gitee.com/Discuz/DiscuzX/issues/I67QWG#note_15422630
> > 
> > 
> > 应用中心反馈说补丁打上了，我重新打开了 Issue ，方便补充一下测试么？
> 
> 还是没有，dismall和新站上还是在报mobile_template_not_found，如图所示：
> 
> ![Screenshot_1673946447](https://user-images.githubusercontent.com/11661760/212855752-6017585d-52a1-4f31-8084-2b9ea0675853.png)
> 
> 在Discuz Hub上也是一样的，应该是还有一个地方出了问题，可能还是discuzcode这个函数的钩子问题

我这里测试环境报错更严重，具体请看截图。
![Screenshot_2023-01-18-08-05-54-077_com kidozh discuzhub](https://user-images.githubusercontent.com/31075951/213039214-5f131bf9-f8c0-4162-9c92-9fbd7365316d.jpg)
![Screenshot_2023-01-18-08-05-59-955_com kidozh discuzhub](https://user-images.githubusercontent.com/31075951/213039268-782b32ef-52c5-4b85-b00a-28aa3d6a0630.jpg)

**Comment by laozhoubuluo** [comment]
> mobile_template_not_found

Hub 版本：https://github.com/kidozh/DiscuzHub/actions/runs/3935007690

Discuz! 程序版本
Discuz! X3.5 Release 20221231 UTF-8
UCenter 客户端版本
UCenter 1.7.0 Release 20221231
服务器系统及 PHP
Linux / PHP v8.2.0
服务器软件
nginx/1.22.1
服务器 MySQL 版本
10.10.2-MariaDB-1:10.10.2+maria~ubu2204

**Comment by kidozh** [comment]
> > > > 似乎官方dismall论坛里的的discuzcode这个问题也没有解决哈哈哈
> > > > https://gitee.com/Discuz/DiscuzX/issues/I67QWG#note_15422630
> > > 
> > > 
> > > 应用中心反馈说补丁打上了，我重新打开了 Issue ，方便补充一下测试么？
> > 
> > 
> > 还是没有，dismall和新站上还是在报mobile_template_not_found，如图所示：
> > ![Screenshot_1673946447](https://user-images.githubusercontent.com/11661760/212855752-6017585d-52a1-4f31-8084-2b9ea0675853.png)
> > 在Discuz Hub上也是一样的，应该是还有一个地方出了问题，可能还是discuzcode这个函数的钩子问题
> 
> 我这里测试环境报错更严重，具体请看截图。 ![Screenshot_2023-01-18-08-05-54-077_com kidozh discuzhub](https://user-images.githubusercontent.com/31075951/213039214-5f131bf9-f8c0-4162-9c92-9fbd7365316d.jpg) ![Screenshot_2023-01-18-08-05-59-955_com kidozh discuzhub](https://user-images.githubusercontent.com/31075951/213039268-782b32ef-52c5-4b85-b00a-28aa3d6a0630.jpg)

这个应该是伪静态没有指定类别，导致返回的json的setting_rewriterule从list变成了string（空“”）导致了类型解析错误，这也是之前那个问题。我本地没有出现这个问题，我晚上去下一下这个测试版本，然后去看看。但是主要原因应该是伪静态页面没有指定导致的。

**Comment by laozhoubuluo** [comment]
> 

我看您是调用了解序列化来解读这个 rewriterule ，但是空值可能没法成功解序列化（新安装的网站这里是空值）。需要判断下如果是空值就跳过序列化。

**Comment by laozhoubuluo** [comment]
> mobile_template_not_found

辛苦您按照 https://gitee.com/laozhoubuluo/DiscuzX/tree/fix/v3.5/mobile_api_viewthread 添加两个模板文件测试下，我这里测试是可以了。

**Comment by kidozh** [comment]
> > 
> 
> 我看您是调用了解序列化来解读这个 rewriterule ，但是空值可能没法成功解序列化（新安装的网站这里是空值）。需要判断下如果是空值就跳过序列化。

我记得里面好像判断过这种情况，但是晚上我回家看看。晚上回去搭一个本地环境然后看看怎么处理这个问题，应该是加一个判断就行了。

**Comment by kidozh** [comment]
> > mobile_template_not_found
> 
> 辛苦您按照 https://gitee.com/laozhoubuluo/DiscuzX/tree/fix/v3.5/mobile_api_viewthread 添加两个模板文件测试下，我这里测试是可以了。

我刚刚测试了一下，全过程都没有问题，从添加到看贴都是渲染正常的。感谢！

![85e2de59bd1e85025818cfa940d0217](https://user-images.githubusercontent.com/11661760/213589138-2edcd7fd-3218-446c-9691-281930a01605.jpg)

这个版本那就没问题了。两个应用应该都是充分的和3.5兼容了。

目前我们做推送我感觉维护两个客户端可能有点麻烦，所以我们目前更倾向于维护“[谈坛](https://github.com/kidozh/discuz_flutter)”，flutter写的，但是可能性能不如原生安卓哈哈哈

**Comment by laozhoubuluo** [comment]
> > > mobile_template_not_found
> > 
> > 
> > 辛苦您按照 https://gitee.com/laozhoubuluo/DiscuzX/tree/fix/v3.5/mobile_api_viewthread 添加两个模板文件测试下，我这里测试是可以了。
> 
> 我刚刚测试了一下，全过程都没有问题，从添加到看贴都是渲染正常的。感谢！
> 
> ![85e2de59bd1e85025818cfa940d0217](https://user-images.githubusercontent.com/11661760/213589138-2edcd7fd-3218-446c-9691-281930a01605.jpg)
> 
> 这个版本那就没问题了。两个应用应该都是充分的和3.5兼容了。
> 
> 目前我们做推送我感觉维护两个客户端可能有点麻烦，所以我们目前更倾向于维护“[谈坛](https://github.com/kidozh/discuz_flutter)”，flutter写的，但是可能性能不如原生安卓哈哈哈

收到，感谢~
