### ISSUE TITLE
git clone下来的源码编译提示错误

### ISSUE THREAD

**Issue by qzznbbs** [kidozh/DiscuzHub#9]
`D:\github\DiscuzHub\app\src\main\AndroidManifest.xml:16:5-83:19: AAPT: error: resource xml/network_security_config (aka com.kidozh.discuzhub:xml/network_security_config) not found.`

**Comment by cxcn2006** [comment]
我也是

**Comment by kidozh** [comment]
我们会在晚上把这个网络配置文件发上来

**Comment by kidozh** [comment]
已提交网络配置文件，可以通过pull更新代码。
